# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


try:
    from PySide2 import QtCore, QtGui, QtWidgets
except:
    from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1084, 566)
        self.label_top = QtWidgets.QLabel(Form)
        self.label_top.setGeometry(QtCore.QRect(10, 10, 1071, 16))
        self.label_top.setStyleSheet("background-color: rgb(34, 194, 255);")
        self.label_top.setAlignment(QtCore.Qt.AlignCenter)
        self.label_top.setObjectName("label_top")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 1071, 501))
        self.tabWidget.setStyleSheet("background-color: rgb(228, 255, 248);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButtonOpenPort = QtWidgets.QPushButton(self.tab)
        self.pushButtonOpenPort.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButtonOpenPort.setObjectName("pushButtonOpenPort")
        self.pushButtonClosePort = QtWidgets.QPushButton(self.tab)
        self.pushButtonClosePort.setGeometry(QtCore.QRect(960, 10, 91, 23))
        self.pushButtonClosePort.setObjectName("pushButtonClosePort")
        self.checkBoxPLC = QtWidgets.QCheckBox(self.tab)
        self.checkBoxPLC.setGeometry(QtCore.QRect(120, 10, 51, 20))
        self.checkBoxPLC.setChecked(True)
        self.checkBoxPLC.setObjectName("checkBoxPLC")
        self.groupBoxAxisSpeed = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisSpeed.setGeometry(QtCore.QRect(10, 40, 471, 161))
        self.groupBoxAxisSpeed.setObjectName("groupBoxAxisSpeed")
        self.label_5 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 67, 17))
        self.label_5.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_5.setObjectName("label_5")
        self.pushButtonSpeedSet = QtWidgets.QPushButton(self.groupBoxAxisSpeed)
        self.pushButtonSpeedSet.setGeometry(QtCore.QRect(243, 74, 89, 31))
        self.pushButtonSpeedSet.setObjectName("pushButtonSpeedSet")
        self.label_3 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_3.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_3.setObjectName("label_3")
        self.textEditXSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditXSpeedSet.setGeometry(QtCore.QRect(110, 23, 91, 31))
        self.textEditXSpeedSet.setObjectName("textEditXSpeedSet")
        self.pushButtonSpeedGet = QtWidgets.QPushButton(self.groupBoxAxisSpeed)
        self.pushButtonSpeedGet.setGeometry(QtCore.QRect(353, 74, 89, 31))
        self.pushButtonSpeedGet.setObjectName("pushButtonSpeedGet")
        self.label = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label.setObjectName("label")
        self.textEditZSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditZSpeedSet.setGeometry(QtCore.QRect(110, 123, 91, 31))
        self.textEditZSpeedSet.setObjectName("textEditZSpeedSet")
        self.textEditYSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditYSpeedSet.setGeometry(QtCore.QRect(110, 73, 91, 31))
        self.textEditYSpeedSet.setObjectName("textEditYSpeedSet")
        self.groupBoxAxisLimit = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisLimit.setGeometry(QtCore.QRect(500, 40, 591, 161))
        self.groupBoxAxisLimit.setObjectName("groupBoxAxisLimit")
        self.pushButtonLimitGet = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonLimitGet.setGeometry(QtCore.QRect(470, 105, 81, 31))
        self.pushButtonLimitGet.setObjectName("pushButtonLimitGet")
        self.label_20 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_20.setGeometry(QtCore.QRect(86, 26, 251, 141))
        self.label_20.setStyleSheet("background-color: rgb(255, 249, 189);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.pushButtonLimitSet = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonLimitSet.setGeometry(QtCore.QRect(360, 105, 81, 31))
        self.pushButtonLimitSet.setObjectName("pushButtonLimitSet")
        self.label_2 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_2.setGeometry(QtCore.QRect(10, 36, 67, 17))
        self.label_2.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_8.setGeometry(QtCore.QRect(10, 136, 67, 17))
        self.label_8.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_4.setGeometry(QtCore.QRect(10, 86, 67, 17))
        self.label_4.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_4.setObjectName("label_4")
        self.label_maxlimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_maxlimit.setGeometry(QtCore.QRect(120, 10, 54, 20))
        self.label_maxlimit.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_maxlimit.setObjectName("label_maxlimit")
        self.label_minlimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_minlimit.setGeometry(QtCore.QRect(243, 10, 54, 20))
        self.label_minlimit.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_minlimit.setObjectName("label_minlimit")
        self.textEditPassword = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditPassword.setGeometry(QtCore.QRect(360, 60, 81, 31))
        self.textEditPassword.setObjectName("textEditPassword")
        self.pushButtonPassword = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonPassword.setGeometry(QtCore.QRect(470, 60, 81, 31))
        self.pushButtonPassword.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.pushButtonPassword.setObjectName("pushButtonPassword")
        self.textEditXMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditXMaxLimit.setGeometry(QtCore.QRect(100, 36, 101, 21))
        self.textEditXMaxLimit.setObjectName("textEditXMaxLimit")
        self.textEditXMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditXMinLimit.setGeometry(QtCore.QRect(220, 35, 101, 21))
        self.textEditXMinLimit.setObjectName("textEditXMinLimit")
        self.textEditYMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditYMinLimit.setGeometry(QtCore.QRect(220, 82, 101, 21))
        self.textEditYMinLimit.setObjectName("textEditYMinLimit")
        self.textEditYMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditYMaxLimit.setGeometry(QtCore.QRect(100, 83, 101, 21))
        self.textEditYMaxLimit.setObjectName("textEditYMaxLimit")
        self.textEditZMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditZMinLimit.setGeometry(QtCore.QRect(220, 134, 101, 21))
        self.textEditZMinLimit.setObjectName("textEditZMinLimit")
        self.textEditZMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditZMaxLimit.setGeometry(QtCore.QRect(100, 135, 101, 21))
        self.textEditZMaxLimit.setObjectName("textEditZMaxLimit")
        self.label_20.raise_()
        self.pushButtonLimitGet.raise_()
        self.pushButtonLimitSet.raise_()
        self.label_2.raise_()
        self.label_8.raise_()
        self.label_4.raise_()
        self.label_maxlimit.raise_()
        self.label_minlimit.raise_()
        self.textEditPassword.raise_()
        self.pushButtonPassword.raise_()
        self.textEditXMaxLimit.raise_()
        self.textEditXMinLimit.raise_()
        self.textEditYMinLimit.raise_()
        self.textEditYMaxLimit.raise_()
        self.textEditZMinLimit.raise_()
        self.textEditZMaxLimit.raise_()
        self.groupBoxMoveCoordiante = QtWidgets.QGroupBox(self.tab)
        self.groupBoxMoveCoordiante.setGeometry(QtCore.QRect(10, 200, 471, 141))
        self.groupBoxMoveCoordiante.setObjectName("groupBoxMoveCoordiante")
        self.textEditxMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditxMove.setGeometry(QtCore.QRect(110, 24, 91, 31))
        self.textEditxMove.setObjectName("textEditxMove")
        self.textEdityMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEdityMove.setGeometry(QtCore.QRect(110, 64, 91, 31))
        self.textEdityMove.setObjectName("textEdityMove")
        self.textEditzMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditzMove.setGeometry(QtCore.QRect(110, 104, 91, 31))
        self.textEditzMove.setObjectName("textEditzMove")
        self.pushButtonMovex = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovex.setGeometry(QtCore.QRect(250, 30, 75, 19))
        self.pushButtonMovex.setObjectName("pushButtonMovex")
        self.pushButtonMovey = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovey.setGeometry(QtCore.QRect(250, 70, 75, 20))
        self.pushButtonMovey.setObjectName("pushButtonMovey")
        self.pushButtonMovez = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovez.setGeometry(QtCore.QRect(250, 110, 75, 19))
        self.pushButtonMovez.setObjectName("pushButtonMovez")
        self.pushButtonGetx = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetx.setGeometry(QtCore.QRect(350, 30, 75, 19))
        self.pushButtonGetx.setObjectName("pushButtonGetx")
        self.pushButtonGety = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGety.setGeometry(QtCore.QRect(350, 70, 75, 19))
        self.pushButtonGety.setObjectName("pushButtonGety")
        self.pushButtonGetz = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetz.setGeometry(QtCore.QRect(350, 110, 75, 19))
        self.pushButtonGetz.setObjectName("pushButtonGetz")
        self.label_10 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_10.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.label_11.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_14.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_14.setObjectName("label_14")
        self.groupBoxAxisStepMove = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisStepMove.setGeometry(QtCore.QRect(500, 200, 341, 141))
        self.groupBoxAxisStepMove.setObjectName("groupBoxAxisStepMove")
        self.label_12 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_12.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_15.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.label_16.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_16.setObjectName("label_16")
        self.pushButtonStepMoveZ = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveZ.setGeometry(QtCore.QRect(230, 109, 75, 19))
        self.pushButtonStepMoveZ.setObjectName("pushButtonStepMoveZ")
        self.textEditStepMoveX = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveX.setGeometry(QtCore.QRect(110, 24, 91, 31))
        self.textEditStepMoveX.setObjectName("textEditStepMoveX")
        self.textEditStepMoveZ = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveZ.setGeometry(QtCore.QRect(110, 104, 91, 31))
        self.textEditStepMoveZ.setObjectName("textEditStepMoveZ")
        self.pushButtonStepMoveY = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveY.setGeometry(QtCore.QRect(230, 69, 75, 20))
        self.pushButtonStepMoveY.setObjectName("pushButtonStepMoveY")
        self.pushButtonStepMoveX = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveX.setGeometry(QtCore.QRect(230, 29, 75, 19))
        self.pushButtonStepMoveX.setObjectName("pushButtonStepMoveX")
        self.textEditStepMoveY = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveY.setGeometry(QtCore.QRect(110, 64, 91, 31))
        self.textEditStepMoveY.setObjectName("textEditStepMoveY")
        self.pushButtonSignalReSet = QtWidgets.QPushButton(self.tab)
        self.pushButtonSignalReSet.setGeometry(QtCore.QRect(220, 10, 111, 23))
        self.pushButtonSignalReSet.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButtonSignalReSet.setObjectName("pushButtonSignalReSet")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 340, 391, 121))
        self.groupBox.setObjectName("groupBox")
        self.radioButtonUSB2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonUSB2.setGeometry(QtCore.QRect(80, 30, 61, 20))
        self.radioButtonUSB2.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSB2.setObjectName("radioButtonUSB2")
        self.radioButtonUSB1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonUSB1.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.radioButtonUSB1.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSB1.setObjectName("radioButtonUSB1")
        self.radioButtonUSBall = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonUSBall.setGeometry(QtCore.QRect(320, 30, 51, 20))
        self.radioButtonUSBall.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSBall.setObjectName("radioButtonUSBall")
        self.pushButtonEnableUSB = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonEnableUSB.setGeometry(QtCore.QRect(10, 90, 75, 19))
        self.pushButtonEnableUSB.setObjectName("pushButtonEnableUSB")
        self.pushButtonDisableUSB = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonDisableUSB.setGeometry(QtCore.QRect(300, 90, 75, 19))
        self.pushButtonDisableUSB.setObjectName("pushButtonDisableUSB")
        self.radioButtonUSB4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonUSB4.setGeometry(QtCore.QRect(240, 30, 61, 20))
        self.radioButtonUSB4.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSB4.setObjectName("radioButtonUSB4")
        self.radioButtonUSB3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonUSB3.setGeometry(QtCore.QRect(160, 30, 61, 20))
        self.radioButtonUSB3.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSB3.setObjectName("radioButtonUSB3")
        self.pushButtonGetPLCVer = QtWidgets.QPushButton(self.tab)
        self.pushButtonGetPLCVer.setGeometry(QtCore.QRect(380, 10, 111, 23))
        self.pushButtonGetPLCVer.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButtonGetPLCVer.setObjectName("pushButtonGetPLCVer")
        self.textEditPLCVer = QtWidgets.QTextEdit(self.tab)
        self.textEditPLCVer.setGeometry(QtCore.QRect(510, 10, 104, 21))
        self.textEditPLCVer.setObjectName("textEditPLCVer")
        self.pushButtonLockDUT = QtWidgets.QPushButton(self.tab)
        self.pushButtonLockDUT.setGeometry(QtCore.QRect(410, 370, 111, 31))
        self.pushButtonLockDUT.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.pushButtonLockDUT.setObjectName("pushButtonLockDUT")
        self.pushButtonUnlockDUT = QtWidgets.QPushButton(self.tab)
        self.pushButtonUnlockDUT.setGeometry(QtCore.QRect(410, 420, 111, 31))
        self.pushButtonUnlockDUT.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.pushButtonUnlockDUT.setObjectName("pushButtonUnlockDUT")
        self.ButtonCurtainOFF = QtWidgets.QPushButton(self.tab)
        self.ButtonCurtainOFF.setGeometry(QtCore.QRect(660, 420, 121, 32))
        self.ButtonCurtainOFF.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCurtainOFF.setObjectName("ButtonCurtainOFF")
        self.ButtonCurtainON = QtWidgets.QPushButton(self.tab)
        self.ButtonCurtainON.setGeometry(QtCore.QRect(660, 370, 121, 32))
        self.ButtonCurtainON.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCurtainON.setObjectName("ButtonCurtainON")
        self.ButtonCylinderIn = QtWidgets.QPushButton(self.tab)
        self.ButtonCylinderIn.setGeometry(QtCore.QRect(530, 420, 121, 32))
        self.ButtonCylinderIn.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCylinderIn.setObjectName("ButtonCylinderIn")
        self.ButtonCylinderOut = QtWidgets.QPushButton(self.tab)
        self.ButtonCylinderOut.setGeometry(QtCore.QRect(530, 370, 121, 32))
        self.ButtonCylinderOut.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCylinderOut.setObjectName("ButtonCylinderOut")
        self.comboBoxLED = QtWidgets.QComboBox(self.tab)
        self.comboBoxLED.setGeometry(QtCore.QRect(800, 420, 151, 31))
        self.comboBoxLED.setStyleSheet("background-color: rgb(22, 160, 255);")
        self.comboBoxLED.setObjectName("comboBoxLED")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.ButtonLEDControl = QtWidgets.QPushButton(self.tab)
        self.ButtonLEDControl.setGeometry(QtCore.QRect(800, 370, 151, 32))
        self.ButtonLEDControl.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonLEDControl.setObjectName("ButtonLEDControl")
        self.textEditBurninTimes = QtWidgets.QTextEdit(self.tab)
        self.textEditBurninTimes.setGeometry(QtCore.QRect(970, 420, 81, 31))
        self.textEditBurninTimes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditBurninTimes.setObjectName("textEditBurninTimes")
        self.ButtonBurninStart = QtWidgets.QPushButton(self.tab)
        self.ButtonBurninStart.setGeometry(QtCore.QRect(970, 370, 81, 32))
        self.ButtonBurninStart.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonBurninStart.setObjectName("ButtonBurninStart")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(850, 200, 201, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButtonCylinderFront = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonCylinderFront.setGeometry(QtCore.QRect(20, 30, 71, 20))
        self.radioButtonCylinderFront.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCylinderFront.setObjectName("radioButtonCylinderFront")
        self.radioButtonCylinderBack = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonCylinderBack.setGeometry(QtCore.QRect(20, 110, 71, 20))
        self.radioButtonCylinderBack.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCylinderBack.setObjectName("radioButtonCylinderBack")
        self.radioButtonCylinderMiddle = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonCylinderMiddle.setGeometry(QtCore.QRect(20, 70, 71, 20))
        self.radioButtonCylinderMiddle.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCylinderMiddle.setObjectName("radioButtonCylinderMiddle")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(840, 240, 201, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButtonCylinderUp = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonCylinderUp.setGeometry(QtCore.QRect(110, 53, 75, 19))
        self.pushButtonCylinderUp.setObjectName("pushButtonCylinderUp")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(730, 234, 201, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButtonUSB1_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonUSB1_3.setGeometry(QtCore.QRect(20, 30, 71, 20))
        self.radioButtonUSB1_3.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSB1_3.setObjectName("radioButtonUSB1_3")
        self.radioButtonUSB3_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonUSB3_3.setGeometry(QtCore.QRect(20, 110, 71, 20))
        self.radioButtonUSB3_3.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSB3_3.setObjectName("radioButtonUSB3_3")
        self.radioButtonUSB2_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonUSB2_3.setGeometry(QtCore.QRect(20, 70, 71, 20))
        self.radioButtonUSB2_3.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSB2_3.setObjectName("radioButtonUSB2_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(840, 240, 201, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButtonCylinderDown = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonCylinderDown.setGeometry(QtCore.QRect(110, 93, 75, 20))
        self.pushButtonCylinderDown.setObjectName("pushButtonCylinderDown")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.ButtonSetYCalLeft = QtWidgets.QPushButton(self.tab_4)
        self.ButtonSetYCalLeft.setGeometry(QtCore.QRect(40, 100, 71, 32))
        self.ButtonSetYCalLeft.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetYCalLeft.setObjectName("ButtonSetYCalLeft")
        self.ButtonSetYCalRight = QtWidgets.QPushButton(self.tab_4)
        self.ButtonSetYCalRight.setGeometry(QtCore.QRect(350, 110, 81, 32))
        self.ButtonSetYCalRight.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetYCalRight.setObjectName("ButtonSetYCalRight")
        self.ButtonSetZCal_2 = QtWidgets.QPushButton(self.tab_4)
        self.ButtonSetZCal_2.setGeometry(QtCore.QRect(170, 141, 111, 21))
        self.ButtonSetZCal_2.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetZCal_2.setObjectName("ButtonSetZCal_2")
        self.pushButton_45 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_45.setGeometry(QtCore.QRect(120, 80, 221, 141))
        self.pushButton_45.setStyleSheet("background-color: rgb(33, 255, 239);")
        self.pushButton_45.setObjectName("pushButton_45")
        self.ButtonSetXCalUp = QtWidgets.QPushButton(self.tab_4)
        self.ButtonSetXCalUp.setGeometry(QtCore.QRect(190, 30, 81, 32))
        self.ButtonSetXCalUp.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetXCalUp.setObjectName("ButtonSetXCalUp")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 10, 491, 441))
        self.groupBox_13.setObjectName("groupBox_13")
        self.ButtonCalZAxisHeight = QtWidgets.QPushButton(self.groupBox_13)
        self.ButtonCalZAxisHeight.setGeometry(QtCore.QRect(250, 360, 191, 41))
        self.ButtonCalZAxisHeight.setStyleSheet("background-color: rgb(41, 255, 229);")
        self.ButtonCalZAxisHeight.setObjectName("ButtonCalZAxisHeight")
        self.ButtonStartCal = QtWidgets.QPushButton(self.groupBox_13)
        self.ButtonStartCal.setGeometry(QtCore.QRect(270, 300, 171, 41))
        self.ButtonStartCal.setStyleSheet("background-color: rgb(41, 255, 229);")
        self.ButtonStartCal.setObjectName("ButtonStartCal")
        self.textEditOffset = QtWidgets.QTextEdit(self.groupBox_13)
        self.textEditOffset.setGeometry(QtCore.QRect(130, 300, 121, 41))
        self.textEditOffset.setObjectName("textEditOffset")
        self.label_39 = QtWidgets.QLabel(self.groupBox_13)
        self.label_39.setGeometry(QtCore.QRect(20, 300, 101, 41))
        self.label_39.setStyleSheet("background-color: rgb(22, 160, 255);")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.ButtonMoveToCalibrationPosition = QtWidgets.QPushButton(self.groupBox_13)
        self.ButtonMoveToCalibrationPosition.setGeometry(QtCore.QRect(20, 360, 211, 41))
        self.ButtonMoveToCalibrationPosition.setStyleSheet("background-color: rgb(41, 255, 229);")
        self.ButtonMoveToCalibrationPosition.setObjectName("ButtonMoveToCalibrationPosition")
        self.ButtonSetXCalDown = QtWidgets.QPushButton(self.groupBox_13)
        self.ButtonSetXCalDown.setGeometry(QtCore.QRect(170, 240, 81, 32))
        self.ButtonSetXCalDown.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetXCalDown.setObjectName("ButtonSetXCalDown")
        self.groupBoxAxisSpeed_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBoxAxisSpeed_3.setGeometry(QtCore.QRect(530, 10, 471, 221))
        self.groupBoxAxisSpeed_3.setObjectName("groupBoxAxisSpeed_3")
        self.label_33 = QtWidgets.QLabel(self.groupBoxAxisSpeed_3)
        self.label_33.setGeometry(QtCore.QRect(10, 130, 67, 17))
        self.label_33.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_33.setObjectName("label_33")
        self.pushButtonPressureSet = QtWidgets.QPushButton(self.groupBoxAxisSpeed_3)
        self.pushButtonPressureSet.setGeometry(QtCore.QRect(243, 74, 89, 31))
        self.pushButtonPressureSet.setObjectName("pushButtonPressureSet")
        self.label_34 = QtWidgets.QLabel(self.groupBoxAxisSpeed_3)
        self.label_34.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_34.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_34.setObjectName("label_34")
        self.textEditPoint1 = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_3)
        self.textEditPoint1.setGeometry(QtCore.QRect(110, 23, 91, 31))
        self.textEditPoint1.setObjectName("textEditPoint1")
        self.pushButtonPressureGet = QtWidgets.QPushButton(self.groupBoxAxisSpeed_3)
        self.pushButtonPressureGet.setGeometry(QtCore.QRect(353, 74, 89, 31))
        self.pushButtonPressureGet.setObjectName("pushButtonPressureGet")
        self.label_35 = QtWidgets.QLabel(self.groupBoxAxisSpeed_3)
        self.label_35.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_35.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_35.setObjectName("label_35")
        self.textEditPoint3 = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_3)
        self.textEditPoint3.setGeometry(QtCore.QRect(110, 123, 91, 31))
        self.textEditPoint3.setObjectName("textEditPoint3")
        self.textEditPoint2 = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_3)
        self.textEditPoint2.setGeometry(QtCore.QRect(110, 73, 91, 31))
        self.textEditPoint2.setObjectName("textEditPoint2")
        self.ButtonPressureLoopTest = QtWidgets.QPushButton(self.groupBoxAxisSpeed_3)
        self.ButtonPressureLoopTest.setGeometry(QtCore.QRect(240, 170, 171, 34))
        self.ButtonPressureLoopTest.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonPressureLoopTest.setObjectName("ButtonPressureLoopTest")
        self.lineEditPressureLoopTest = QtWidgets.QLineEdit(self.groupBoxAxisSpeed_3)
        self.lineEditPressureLoopTest.setGeometry(QtCore.QRect(112, 174, 91, 31))
        self.lineEditPressureLoopTest.setObjectName("lineEditPressureLoopTest")
        self.ButtonSetZCal = QtWidgets.QPushButton(self.tab_4)
        self.ButtonSetZCal.setGeometry(QtCore.QRect(180, 170, 111, 21))
        self.ButtonSetZCal.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetZCal.setObjectName("ButtonSetZCal")
        self.groupBox_13.raise_()
        self.ButtonSetYCalLeft.raise_()
        self.ButtonSetYCalRight.raise_()
        self.ButtonSetZCal_2.raise_()
        self.pushButton_45.raise_()
        self.ButtonSetXCalUp.raise_()
        self.groupBoxAxisSpeed_3.raise_()
        self.ButtonSetZCal.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        self.label_bottom = QtWidgets.QLabel(Form)
        self.label_bottom.setGeometry(QtCore.QRect(10, 540, 1071, 20))
        self.label_bottom.setStyleSheet("background-color: rgb(34, 194, 255);")
        self.label_bottom.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bottom.setObjectName("label_bottom")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Bojayo6Touch"))
        self.label_top.setText(_translate("Form", "Bojay o6Touch UI V1.0"))
        self.pushButtonOpenPort.setText(_translate("Form", "OpenPort"))
        self.pushButtonClosePort.setText(_translate("Form", "ClosePort"))
        self.checkBoxPLC.setText(_translate("Form", "PLC"))
        self.groupBoxAxisSpeed.setTitle(_translate("Form", "Axis Speed"))
        self.label_5.setText(_translate("Form", "Z Axis"))
        self.pushButtonSpeedSet.setText(_translate("Form", "Set"))
        self.label_3.setText(_translate("Form", "Y Axis"))
        self.pushButtonSpeedGet.setText(_translate("Form", "Get"))
        self.label.setText(_translate("Form", "X Axis"))
        self.groupBoxAxisLimit.setTitle(_translate("Form", "Axis Limit"))
        self.pushButtonLimitGet.setText(_translate("Form", "Get"))
        self.pushButtonLimitSet.setText(_translate("Form", "Set"))
        self.label_2.setText(_translate("Form", "X Axis"))
        self.label_8.setText(_translate("Form", "Z Axis"))
        self.label_4.setText(_translate("Form", "Y Axis"))
        self.label_maxlimit.setText(_translate("Form", "MaxLimit"))
        self.label_minlimit.setText(_translate("Form", "MinLimit"))
        self.pushButtonPassword.setText(_translate("Form", "Password"))
        self.groupBoxMoveCoordiante.setTitle(_translate("Form", "Move Coordinate"))
        self.pushButtonMovex.setText(_translate("Form", "Move X"))
        self.pushButtonMovey.setText(_translate("Form", "Move Y"))
        self.pushButtonMovez.setText(_translate("Form", "Move Z"))
        self.pushButtonGetx.setText(_translate("Form", "Get X"))
        self.pushButtonGety.setText(_translate("Form", "Get Y"))
        self.pushButtonGetz.setText(_translate("Form", "Get Z"))
        self.label_10.setText(_translate("Form", "X Axis"))
        self.label_11.setText(_translate("Form", "Z Axis"))
        self.label_14.setText(_translate("Form", "Y Axis"))
        self.groupBoxAxisStepMove.setTitle(_translate("Form", "Set step"))
        self.label_12.setText(_translate("Form", "X Axis"))
        self.label_15.setText(_translate("Form", "Y Axis"))
        self.label_16.setText(_translate("Form", "Z Axis"))
        self.pushButtonStepMoveZ.setText(_translate("Form", "Move Z"))
        self.pushButtonStepMoveY.setText(_translate("Form", "Move Y"))
        self.pushButtonStepMoveX.setText(_translate("Form", "Move X"))
        self.pushButtonSignalReSet.setText(_translate("Form", "SignalReSet"))
        self.groupBox.setTitle(_translate("Form", "USB Module"))
        self.radioButtonUSB2.setText(_translate("Form", "USB2"))
        self.radioButtonUSB1.setText(_translate("Form", "USB1"))
        self.radioButtonUSBall.setText(_translate("Form", "All"))
        self.pushButtonEnableUSB.setText(_translate("Form", "EnableUSB"))
        self.pushButtonDisableUSB.setText(_translate("Form", "DisabelUSB"))
        self.radioButtonUSB4.setText(_translate("Form", "USB4"))
        self.radioButtonUSB3.setText(_translate("Form", "USB3"))
        self.pushButtonGetPLCVer.setText(_translate("Form", "ReadPCLVer"))
        self.pushButtonLockDUT.setText(_translate("Form", "LockDUT"))
        self.pushButtonUnlockDUT.setText(_translate("Form", "UnlockDUT"))
        self.ButtonCurtainOFF.setText(_translate("Form", "LightCurtainOFF"))
        self.ButtonCurtainON.setText(_translate("Form", "LightCurtainON"))
        self.ButtonCylinderIn.setText(_translate("Form", "Cylinder in"))
        self.ButtonCylinderOut.setText(_translate("Form", "Cylinder out"))
        self.comboBoxLED.setItemText(0, _translate("Form", "1-red-on"))
        self.comboBoxLED.setItemText(1, _translate("Form", "1-red-off"))
        self.comboBoxLED.setItemText(2, _translate("Form", "1-yellow-on"))
        self.comboBoxLED.setItemText(3, _translate("Form", "1-yellow-off"))
        self.comboBoxLED.setItemText(4, _translate("Form", "1-green-on"))
        self.comboBoxLED.setItemText(5, _translate("Form", "1-green-off"))
        self.comboBoxLED.setItemText(6, _translate("Form", "2-red-on"))
        self.comboBoxLED.setItemText(7, _translate("Form", "2-red-off"))
        self.comboBoxLED.setItemText(8, _translate("Form", "2-green-on"))
        self.comboBoxLED.setItemText(9, _translate("Form", "2-green-off"))
        self.comboBoxLED.setItemText(10, _translate("Form", "2-yellow-on"))
        self.comboBoxLED.setItemText(11, _translate("Form", "2-yellow-off"))
        self.comboBoxLED.setItemText(12, _translate("Form", "3-red-on"))
        self.comboBoxLED.setItemText(13, _translate("Form", "3-red-off"))
        self.comboBoxLED.setItemText(14, _translate("Form", "3-green-on"))
        self.comboBoxLED.setItemText(15, _translate("Form", "3-green-off"))
        self.comboBoxLED.setItemText(16, _translate("Form", "3-yellow-on"))
        self.comboBoxLED.setItemText(17, _translate("Form", "3-yellow-off"))
        self.comboBoxLED.setItemText(18, _translate("Form", "4-red-on"))
        self.comboBoxLED.setItemText(19, _translate("Form", "4-red-off"))
        self.comboBoxLED.setItemText(20, _translate("Form", "4-green-on"))
        self.comboBoxLED.setItemText(21, _translate("Form", "4-green-off"))
        self.comboBoxLED.setItemText(22, _translate("Form", "4-yellow-on"))
        self.comboBoxLED.setItemText(23, _translate("Form", "4-yellow-off"))
        self.ButtonLEDControl.setText(_translate("Form", "LEDControl"))
        self.ButtonBurninStart.setText(_translate("Form", "LoopTest"))
        self.groupBox_2.setTitle(_translate("Form", "ZaxisCylinderModule"))
        self.radioButtonCylinderFront.setText(_translate("Form", "Front"))
        self.radioButtonCylinderBack.setText(_translate("Form", "Back"))
        self.radioButtonCylinderMiddle.setText(_translate("Form", "Middle"))
        self.groupBox_3.setTitle(_translate("Form", "ZaxisCylinderModule"))
        self.pushButtonCylinderUp.setText(_translate("Form", "Up"))
        self.groupBox_4.setTitle(_translate("Form", "ZaxisCylinderModule"))
        self.radioButtonUSB1_3.setText(_translate("Form", "Front"))
        self.radioButtonUSB3_3.setText(_translate("Form", "back"))
        self.radioButtonUSB2_3.setText(_translate("Form", "middle"))
        self.groupBox_5.setTitle(_translate("Form", "ZaxisCylinderModule"))
        self.pushButtonCylinderDown.setText(_translate("Form", "Down"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "PLC"))
        self.ButtonSetYCalLeft.setText(_translate("Form", "Set Left"))
        self.ButtonSetYCalRight.setText(_translate("Form", "Set Right"))
        self.ButtonSetZCal_2.setText(_translate("Form", "Set Z "))
        self.pushButton_45.setText(_translate("Form", "I am calibration KIT"))
        self.ButtonSetXCalUp.setText(_translate("Form", "Set Up"))
        self.groupBox_13.setTitle(_translate("Form", "Calibration"))
        self.ButtonCalZAxisHeight.setText(_translate("Form", "CalZAxisHeight"))
        self.ButtonStartCal.setText(_translate("Form", "Start Calibration"))
        self.label_39.setText(_translate("Form", "ZAxisOffset"))
        self.ButtonMoveToCalibrationPosition.setText(_translate("Form", "Move to Calibration Position"))
        self.ButtonSetXCalDown.setText(_translate("Form", "Set down"))
        self.groupBoxAxisSpeed_3.setTitle(_translate("Form", "Pressure"))
        self.label_33.setText(_translate("Form", "Point3"))
        self.pushButtonPressureSet.setText(_translate("Form", "Set"))
        self.label_34.setText(_translate("Form", "Point2"))
        self.pushButtonPressureGet.setText(_translate("Form", "Get"))
        self.label_35.setText(_translate("Form", "Point1"))
        self.ButtonPressureLoopTest.setText(_translate("Form", "PressureLoopTest"))
        self.ButtonSetZCal.setText(_translate("Form", "Set Z "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Cal"))
        self.label_bottom.setText(_translate("Form", "Developed by Bojay"))
